import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const {
            productBase64,
            mode, // "white-background" or "with-model"
            gender, // "Hombre" or "Mujer" (if mode is "with-model")
            instructions, // user instructions for model and background
            apiKey,
            format, // "1:1", "4:5", or "9:16"
        } = body;

        if (!productBase64 || !apiKey || !mode) {
            return NextResponse.json(
                { error: "Faltan parámetros requeridos: imagen, modo o API Key" },
                { status: 400 }
            );
        }

        const genAI = new GoogleGenerativeAI(apiKey);

        // Extraer formato del base64 (ej: data:image/png;base64,...)
        const mimeTypeMatches = productBase64.match(/^data:(.*);base64,/);
        const mimeType = mimeTypeMatches ? mimeTypeMatches[1] : "image/jpeg";
        const base64Data = productBase64.split(",")[1] || productBase64;

        try {
            const model = genAI.getGenerativeModel({
                model: "gemini-3.1-flash-image-preview",
                generationConfig: {
                    responseModalities: ["IMAGE"],
                } as any
            }, { apiVersion: "v1" });

            let prompt = "";
            let formatInstruction = "";
            if (format === "4:5") formatInstruction = "IMAGE DIMENSIONS / ASPECT RATIO: 4:5 (Vertical/Retrato).";
            else if (format === "9:16") formatInstruction = "IMAGE DIMENSIONS / ASPECT RATIO: 9:16 (Formato Historia/Stories).";
            else formatInstruction = "IMAGE DIMENSIONS / ASPECT RATIO: 1:1 (Cuadrado).";

            if (mode === "white-background") {
                prompt = `
Toma esta imagen de producto y genera una versión estrictamente profesional.
INDICACIONES:
- El fondo debe ser COMPLETAMENTE BLANCO.
- Ajusta la iluminación y la corrección de color para que el producto luzca premium y publicitario.
- Elimina ruidos, sombras duras no deseadas u objetos de fondo de la imagen original.
- El producto debe verse centrado y nítido.
${formatInstruction}
                `;
            } else if (mode === "with-model") {
                prompt = `
Toma este producto y genera una foto fotorrealista donde interactúe con un modelo.
INDICACIONES:
- Modelo: ${gender}.
- Contexto y apariencia: ${instructions || "Modelo profesional utilizando o interactuando naturalmente con el producto en un contexto de uso adecuado."}
- El producto debe integrarse perfectamente en el entorno (iluminación, sombras, reflejos).
- Calidad de fotografía comercial, aspecto natural y convincente para un anuncio de e-commerce o redes sociales.
- Mantén el producto original como el centro de atención.
${formatInstruction}
                `;
            }

            // Generamos una sola imagen
            const generatedImages = await Promise.all(
                Array.from({ length: 1 }).map(async (_, index) => {
                    try {
                        const variationPrompt = index === 0
                            ? prompt
                            : `${prompt}\n\nAñade una ligera variación en la perspectiva, composición o iluminación para ofrecer más opciones (Variación ${index + 1}).`;

                        const result = await model.generateContent([
                            {
                                inlineData: {
                                    data: base64Data,
                                    mimeType: mimeType,
                                },
                            },
                            variationPrompt,
                        ]);

                        const response = await result.response;
                        const parts = response.candidates?.[0]?.content?.parts || [];
                        const imagePart = parts.find((part: any) => part.inlineData);

                        if (imagePart?.inlineData) {
                            return {
                                image: `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`,
                                title: mode === "white-background" ? "Fondo Blanco" : `Modelo ${gender}`
                            };
                        }

                        throw new Error("No image generated by Gemini");
                    } catch (err) {
                        console.error(`Error generando variación ${index}:`, err);
                        return null; // Filtraremos nulos más adelante
                    }
                })
            );

            const validImages = generatedImages.filter(img => img !== null);

            if (validImages.length === 0) {
                throw new Error("La IA no pudo procesar y generar imágenes válidas. Revisa tu prompt o la política de la API.");
            }

            return NextResponse.json({
                success: true,
                variations: validImages,
            });

        } catch (error: any) {
            console.error("Error interactuando con Gemini API:", error);
            return NextResponse.json(
                { error: "Error de IA colaborativa. Intenta usar menos instrucciones o verificar tu API Key." },
                { status: 500 }
            );
        }
    } catch (error: any) {
        console.error("Error in photo-studio API:", error);
        return NextResponse.json(
            { error: "Error interno del servidor", details: error.message },
            { status: 500 }
        );
    }
}
